### ISSUE TITLE
Unknown filetype vue-something in .vue

### ISSUE THREAD

**Issue by aiya000** [osyo-manga/vim-precious#17]
.vue中の`script lang="ts"`のTypeScriptで行数を多くし、かつ戻り値に`Promise<something>`を指定すると、その行より下に行った際に`vue-something`というファイルタイプが設定されます :(

謎のファイルタイプなので、シンタックスハイライトが消失し…… x)

### 再現

- 1. 下記ファイルの「行X」へカーソルを移動する

```vue
<template>
    <Label text="hi" />
</template>

<script lang="ts">
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a
// a

class Foo {
  public async f(): Promise<void> {}
}

function bar(): void {}
</script>
```

**Comment by aiya000** [comment]
`// a`は行数を増やすためのダミーで、実際はimportやclass内でのメソッド定義などで行数が増えた場合などに、問題がおきます :joy:

**Comment by osyo-manga** [comment]
ありがとうございます。
詳しくはみてないんですが、おそらく `context_filetype.vim` の[ここら辺](https://github.com/Shougo/context_filetype.vim/blob/c3f806b4d06230607bc0a3bf619bf9c3ec1c9d95/autoload/context_filetype.vim#L206-L210) の設定で意図しない `filetype` として認識されているのかあ、と思います。
該当する行で `:echo context_filetype#get()` を呼ぶとわかりやすいと思います。

**Comment by aiya000** [comment]
ありがとうございます！
`public async f(): Promise<void> {}`の行で実行したところ
```
{'range': [[0, 0], [0, 0]], 'filetype': 'vue'}
```
とのことで、その1つ下の行で実行すると
```
{'range': [[0, 0], [0, 0]], 'filetype': 'vue-void'}
```
とのことでした。

とりあえず、こんなワークアラウンドで解決してみましたw

```vim
augroup vimrc
  autocmd User PreciousFileType call s:dont_enter_vue_promise()
augroup END

function! s:dont_enter_vue_promise() abort
  if context_filetype#get()['filetype'] =~# '^vue-'
    call precious#switch('typescript')
  endif
endfunction
```

P.S.  
僕はNativeScript-Vueっていうのでvue.jsに触れているのですが、preciousが`<template>`部では`html`に・`script lang="ts"`部では`typescript`に設定してくれて、満足です。  
つまるところ、`vue-foo`っていうファイルタイプって、なんのことだろう？　って感じなので、もしかしたら、不要なのかも……？  
（すみません、よくわかっていません。）

**Comment by aiya000** [comment]
ところで、こんなに素敵なプラグインをありがとうございます！
NativeScript-Vueを書く上で、と〜〜っても助かっております 🕶

**Comment by osyo-manga** [comment]
> とりあえず、こんなワークアラウンドで解決してみましたw

なるほど。基本的に `filetype` まわりの設定は context_filetype.vim に依存しているので、この手の問題は context_filetype.vim 側で対処するべきかな、とは思っています。

> つまるところ、vue-fooっていうファイルタイプって、なんのことだろう？　って感じなので、もしかしたら、不要なのかも……？
導入された経緯はこれっぽいですね https://github.com/Shougo/context_filetype.vim/issues/38

> ところで、こんなに素敵なプラグインをありがとうございます！

ありがとうございます :)

**Comment by osyo-manga** [comment]
あ、あと `g:context_filetype#filetypes` でユーザ側でカスタマイズ出来るのでそっちで対応してもいいかもしれません。

**Comment by aiya000** [comment]
助かりました、ありがとうございます :pray:
context_filetype.vim問題っぽいので、closeします :D
