### ISSUE TITLE
バッファが取り除かれる際の filetype のリセットが狙いとするバッファではないところで行われる

### ISSUE THREAD

**Issue by siaa4fu** [osyo-manga/vim-precious#21]
こんにちは、便利に使わせてもらっています！

filetype が base_filetype から切り替わっているときにカレントバッファ以外を取り除くと、カレントバッファで filetype のリセットが起こってしまうことがあるので報告です。

# 例

具体的には、以下の様な toml ファイルを開いたとします。

``` toml
[[plugins]]
repo = 'test'
hook_add = '''
  let s:foo = 'bar'
'''
```

カーソルが `hook_add` 内にあるとき、 base_filetype である `toml` から context_filetype である `vim` に切り替わっています。このとき、例えば以下の操作のいずれかを行うと base_filetype へのリセットが起こります。

* `CTRL-W o` によって他のバッファを閉じる
* `:call popup_notification('test', {})` でポップアップを開いてから閉じられるまで待つ
* ...などなど

# 修整

問題は `BufWinLeave` 時の自動コマンドが、取り除かれつつあるバッファではなくカレントバッファで実行されることが原因です。実行すべきバッファを指定することで解決できました。

# その他

また、以下の修整を加えています。

* filetype のリセットは `precious#autocmd_switch()` を使う
  * 切り替えに伴い、きちんと `b:precious_prev_context_filetype` が上書きされるように
* 重複する `BufWinLeave` 自動コマンドを削除
  * 内容的に全く同じ処理を行っていたので取り除いた

以上です

**Comment by siaa4fu** [comment]
あ、重複していて削除したのは `BufWinEnter` です。間違えました

**Comment by osyo-manga** [comment]
ありがとうございます。マージしました。
